"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userRouter = exports.authRouter = void 0;
const express_1 = require("express");
const auth_1 = require("../../core/auth");
const validate_1 = require("../../core/validate");
const asyncHandler_1 = require("../../core/asyncHandler");
const user_dto_1 = require("./user.dto");
const user_controller_1 = require("./user.controller");
const authRouter = (0, express_1.Router)();
exports.authRouter = authRouter;
const userRouter = (0, express_1.Router)();
exports.userRouter = userRouter;
authRouter.post("/signup", (0, validate_1.validate)(user_dto_1.SignupDto), (0, asyncHandler_1.ah)(user_controller_1.signup));
authRouter.post("/login", (0, validate_1.validate)(user_dto_1.LoginDto), (0, asyncHandler_1.ah)(user_controller_1.login));
authRouter.post("/logout", (0, auth_1.auth)(), (0, asyncHandler_1.ah)(user_controller_1.logout));
//authRouter.post("/logout", ah(logout));
authRouter.get("/me", (0, auth_1.auth)(), (0, asyncHandler_1.ah)(user_controller_1.me));
authRouter.post("/refresh", (0, asyncHandler_1.ah)(user_controller_1.refresh));
userRouter.post("/createUser", (0, auth_1.auth)(), auth_1.checkAdmin, (0, validate_1.validate)(user_dto_1.CreateUserDto), (0, asyncHandler_1.ah)(user_controller_1.createUser));
